[package]
name = "expenses"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
rusqlite = { version = "0.37.0", features = ["chrono"] }
